name: On push

on:
  push:
    branches:
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    env:
      wiki-dir: ./wiki
      submodule-dir: ./self_updating_wiki.wiki
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0
      - name: Copy wiki/ to submodule
        run: cp -r wiki/. self_updating_wiki.wiki/
      - working-directory: ${{env.submodule-dir}}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout master
          rm -r *
          git add .
          git commit -m "Update wiki from master"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/dracco1993/self_updating_wiki.wiki.git"
