name: On push

on:
  push:
    branches:
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    env:
      wiki-dir: ./wiki
      submodule-dir: ./self_updating_wiki.wiki

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0
      - name: Copy docs/ to submodule
        run: cp -r wiki/. self_updating_wiki.wiki/
      - run: touch outer_file.txt
      - run: cd self_updating_wiki.wiki/
      - working-directory: ${{env.submodule-dir}}
        run: |
          touch sub_file.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout master
          git add .
          git commit -m "Update wiki from master"
          git push
