name: On push

on:
  push:
    branches:
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Copy docs/ to submodule
        run: cp -r wiki/ self_updating_wiki.wiki/
      - run: cd self_updating_wiki.wiki
      - run: git add .
      - run: git commit -m "Updated wiki from main repo"
      - run: git push
