name: On push

on:
  push:
    branches:
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0
      - name: Copy docs/ to submodule
        run: cp -r wiki/. self_updating_wiki.wiki/
      - run: cd self_updating_wiki.wiki
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: touch test_file.txt
      - run: git add .
      - run: git commit -m "Update wiki from master"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
